### PR TITLE
completed issue #16

### LINKED ISSUE #16: Take user input for port
Right now the PORT on which the server is hosted is hardcoded. Take PORT no as input from the user and check if it is correct and available then host a server on that port otherwise display an error message.

### PR DESCRIPTION
**Pull request by yashkathe**
# Fixed #16

- Takes user input before hosting the server
- Scans the port if it is already in use. If the port is open it throws an error and closes the app
- If it is not in use it starts the server

### CODE REVIEW

**Comment by achhayapathak** [comment]
Please make the changes on the client side as the port is hardcoded as well, merging this will break the application.

**Comment by achhayapathak** [comment]
Also, the port no should be greater than 1025. Ports from 1 to 1025 are reserved by the system, you can read more about this.

**Comment by achhayapathak** [comment]
Also, can you create a function which has all the logic of port validation and server creation? You can create a separate file to store this function and import it into server.js file. Functional programming is a very standard practice in software development and as a rule of thumb, we don't exceed the number of lines more than 100 in a single file. As server.js is our main file for hosting the server it will be good to write functions and import them already as it is easy to read and maintain. You can take inspiration from the client folder. Also, try to add some comments so that it's easier to onboard others. Thanks!

**Comment by yashkathe** [comment]
> Also, can you create a function which has all the logic of port validation and server creation? You can create a separate file to store this function and import it into server.js file. Functional programming is a very standard practice in software development and as a rule of thumb, we don't exceed the number of lines more than 100 in a single file. As server.js is our main file for hosting the server it will be good to write functions and import them already as it is easy to read and maintain. You can take inspiration from the client folder. Also, try to add some comments so that it's easier to onboard others. Thanks!

Sure, I'll create a separate function

**Comment by yashkathe** [comment]
- Added separate file with functions for getting user input and validating the port on the host side
- Program asks the client to enter the port number for connecting to the host server

**Comment by achhayapathak** [comment]
The code looks good to me, have you tried to run this locally? Was it working as expected?

**Comment by yashkathe** [comment]
> The code looks good to me, have you tried to run this locally? Was it working as expected?

Yes, everything works as expected. I tested and then committed the code

**Review by achhayapathak — APPROVED** [review]
LGTM

**Pull request merged**
